import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {FaGithub, FaLinkedin} from "react-icons/fa";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dajeong's Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="bg-gray-900 text-white y-16">
            <header className="fixed top-0 w-full bg-gray-900 bg-opacity-90 z-50 shadow-md">
                <nav className="max-w-5xl mx-auto px-4 py-4 flex justify-between items-center">
                    <h1 className="text-xl font-bold"><a href="#hero">Dajeong Kim</a></h1>
                    <div className="space-x-4">
                        <a href="#about" className="hover:text-teal-400">About</a>
                        <a href="#experience" className="hover:text-teal-400">Experience</a>
                        <a href="#projects" className="hover:text-teal-400">Projects</a>
                        <a href="#skills" className="hover:text-teal-400">Skills</a>
                    </div>
                </nav>
            </header>
            {/*<main className="pt-24 px-4 max-w-5xl mx-auto">{children}</main>*/}
            {/*<footer className="py-6 text-center text-gray-500">*/}
            {/*    <div className="flex justify-center space-x-4 mb-2">*/}
            {/*        <a href="https://github.com/yourusername" target="_blank" rel="noreferrer">*/}
            {/*            <FaGithub size={20}/>*/}
            {/*        </a>*/}
            {/*        <a href="https://linkedin.com/in/yourusername" target="_blank" rel="noreferrer">*/}
            {/*            <FaLinkedin size={20}/>*/}
            {/*        </a>*/}
            {/*    </div>*/}
            {/*    <p>&copy; 2025 Your Name. All rights reserved.</p>*/}
            {/*</footer>*/}
        </div>
        {children}
        </body>
        </html>
    );
}
